name: Build RetroArch Core for Switch

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/toolchain-base:latest

    steps:
    - name: Checkout this repo
    - uses: actions/checkout@v3.0.0

    - name: Build
      run: |
        cd /root/workspace
        git submodule init
        git submodule update
        git clone https://github.com/libretro/libretro-super.git
        cd libretro-super
        ./libretro-buildbot-recipe.sh ../core-melonds
        pwd
        cd dist/unix
        for i in *.a; do cp ../info/\${i%.*}.info .; done
        ls -lah ./"

    - name: Upload the build artifacts
      uses: actions/upload-artifact@v3.0.0
      with:
        name: MelonDS core with JIT enabled for libNX
        path: libretro-super/dist/unix/*
        if-no-files-found: error
        retention-days: 90
